import asyncio
import uuid
import yaml
from pathlib import Path
from typing import List

import vertexai
from vertexai.language_models import TextEmbeddingModel
from sqlalchemy.ext.asyncio import AsyncSession

# Imports from our local backend modules
from database import AsyncSessionFactory, CONFIG_PATH
from models import Document, Embedding

def load_config():
    try:
        with open(CONFIG_PATH, "r") as f:
            return yaml.safe_load(f)
    except Exception as e:
        print(f"Error loading config.yaml: {e}")
        return {}

class RecursiveCharacterTextSplitter:
    """A simplistic recursive character text splitter for chunking documents."""
    def __init__(self, chunk_size: int = 1000, chunk_overlap: int = 100):
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap
        self.separators = ["\n\n", "\n", " ", ""]

    def split_text(self, text: str) -> List[str]:
        final_chunks = []
        start = 0
        while start < len(text):
            end = start + self.chunk_size
            if end >= len(text):
                final_chunks.append(text[start:].strip())
                break
                
            split_at = end
            for sep in self.separators:
                if sep == "":
                    continue
                pos = text.rfind(sep, start, end)
                if pos != -1 and pos > start:
                    split_at = pos + len(sep)
                    break
            
            chunk = text[start:split_at].strip()
            if chunk:
                final_chunks.append(chunk)

            # Advance start pointer, ensuring progress even with large overlap
            next_start = split_at - self.chunk_overlap
            start = max(start + 1, next_start) 

        return [c for c in final_chunks if c]


async def ingest_document(
    db: AsyncSession, 
    raw_text: str, 
    user_id: uuid.UUID, 
    title: str = "Untitled Document"
) -> uuid.UUID:
    """Ingests raw text, splits it, gets embeddings, and saves to database."""
    config = load_config()
    
    # Extract Vertex config
    project_id = config.get("gcp_project_id")
    location = config.get("gcp_location", "us-central1")
    
    # Initialize Vertex AI
    vertexai.init(project=project_id, location=location)
    
    # Defaulting to 768 dimension model per user requirement / config
    model_name = config.get("models", {}).get("vector_search", "text-embedding-004")
    embedding_model = TextEmbeddingModel.from_pretrained(model_name)

    # Determine PII flag
    pii_flag = False
    if "PII" in raw_text or "Confidential" in raw_text:
        pii_flag = True

    # Chunking
    splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
    chunks = splitter.split_text(raw_text)

    # Database transaction: Create core document
    new_doc = Document(
        title=title,
        content=raw_text,
        pii_flag=pii_flag
    )
    db.add(new_doc)
    await db.flush()  # We need the doc_id generated by the database

    # Vectorize and save chunks
    for i, chunk in enumerate(chunks):
        # We process sequentially for safety. In production, consider batching:
        # embedding_model.get_embeddings(chunks)
        embedding_res = embedding_model.get_embeddings([chunk], output_dimensionality=768)
        vector = embedding_res[0].values

        new_embedding = Embedding(
            doc_id=new_doc.doc_id,
            chunk_id=f"chunk_{i}",
            text_chunk=chunk,
            embedding=vector
        )
        db.add(new_embedding)

    await db.commit()
    return new_doc.doc_id

async def main():
    print("Starting ingestion test...")
    # This requires AlloyDB to be reachable and google-cloud-aiplatform configured
    try:
        async with AsyncSessionFactory() as db:
            test_text = "This is a PII containing test document.\n" + ("It has multiple lines and words to test chunking logic. " * 30)
            test_user_id = uuid.uuid4()
            print(f"Generating chunks and vectors...")
            doc_id = await ingest_document(db, test_text, test_user_id, "Vertex AI Test Doc")
            print(f"[SUCCESS] Successfully ingested doc and vectors! Doc ID: {doc_id}")
    except Exception as e:
        print(f"[ERROR] Ingestion failed: {e}")

if __name__ == "__main__":
    asyncio.run(main())
